### ISSUE TITLE
No css!?

### ISSUE THREAD

**Issue by ParoTheParrot** [messagerie-melanie2/Roundcube-Plugin-Mobile#1]
After installing both mobile plugin and "melanie2_larry_mobile" skin the login screen looks good, but after login no css is loaded! I only see bullet points!
![clipboard](https://cloud.githubusercontent.com/assets/5046600/7494607/f82bcf9c-f408-11e4-8381-a6587bd71d86.jpg)

**Comment by tpayen** [comment]
Hi. You also have to install the jquery_mobile plugin

**Comment by ParoTheParrot** [comment]
this isn't mentioned under Installation in Readme.md
I'll try it...! -> Now I've installed two plugins: 'jquery_mobile', 'mobile'. But it does not work properly:
1) Errorlog: 
[06-May-2015 19:45:31 UTC] PHP Warning:  in_array() expects parameter 2 to be array, null given in /homepages/4/d23988710//XXX/roundcube/plugins/mobile/mobile.php on line 118
2) Logout - login does not work
3) Standard theme is "cluttered"

**Comment by tpayen** [comment]
https://github.com/messagerie-melanie2/roundcube_mobile/blob/master/README.md
You have to rename config.inc.php.dist.php file in mobile plugin to config.inc.php

**Comment by ParoTheParrot** [comment]
Still not satisfying:
1.) Login does not work (hang up)
2.) Layout clutterd
3.) switsching "mobile.mobile" also hung up"

**Comment by tpayen** [comment]
Which roundcube version are you using ?
Can you show us a screenshot of the "Layout clutterd" ?

**Comment by tpayen** [comment]
Hello, I just update the melanie2_larry_mobile skin and the mobile plugin. It might improve the compatibility with Roundcube 1.1.1, can you make a try ?
