### ISSUE TITLE
feature request: add "create group" to address book in melanie2 skin

### ISSUE THREAD

**Issue by johnwayne4d** [messagerie-melanie2/Roundcube-Plugin-Mobile#13]
@tpayen feature request: add "create group" to address book in melanie2 skin.
i think im close to adding it myself..
i edited the /templates/addressbook.html adding the lines
`<div class="ui-block-a">
				<roundcube:button command="group-create" type="link" title="newgroup" class="listbutton add jqm-mail-button-newcontact ui-link ui-btn ui-btn-a ui-alt-icon ui-icon-plus ui-btn-icon-left ui-corner-all" innerClass="inner" label="newgroup" />
			</div>`
immediately under the lines
`<div class="ui-block-a">
				<roundcube:button command="add" type="link" title="newcontact" class="listbutton add jqm-mail-button-newcontact ui-link ui-btn ui-btn-a ui-alt-icon ui-icon-plus ui-btn-icon-left ui-corner-all" innerClass="inner" label="newcontact" />
			</div>`
but nothing happens, roundcube desktop view uses a dialog window instead of a page to create a new group, so i am missing some step to produce that dialog in mobile.

**Comment by tpayen** [comment]
It'll probably need to adapt the "create group" dialog to a mobile dialog.
I look at this asap.

**Comment by tpayen** [comment]
Added with the new 0.4.6 release for plugin and skin
