### ISSUE TITLE
Translation to spanish

### ISSUE THREAD

**Issue by gaguileram** [messagerie-melanie2/Roundcube-Plugin-Mobile#14]
The plugin lacks of spanish translation. To solve it I have created the file "localization/es_ES.inc" with this content:

$labels = array();
$labels['mobile'] = 'Vista móvil';
$labels['desktop'] = 'Vista escritorio';
$labels['pull_to_refresh'] = 'Pulsar para refrescar';
$labels['release_to_refresh'] = 'Soltar para refrescar';
$labels['slide to delete message'] = 'Deslizar para borrar mensaje';
$labels['release to delete message'] = 'Soltar para borrar mensaje';
$labels['slide to mark as read'] = 'Deslizar para marcar como leído';
$labels['release to mark as read'] = 'Soltar para marcar como leído';
$labels['slide to mark as unread'] = 'Deslizar para marcar como no leído';
$labels['release to mark as unread'] = 'Soltar para marcar como no leído';

**Comment by tpayen** [comment]
Thanks!

**Comment by tpayen** [comment]
Added in 0.4.6
