### ISSUE TITLE
Request Filter "flagged"

### ISSUE THREAD

**Issue by metalzone82** [messagerie-melanie2/Roundcube-Plugin-Mobile#15]
it's possible to insert (near search toolbar) the Filter "all/unflagged/flagged"
 etc?
thanks

![unflagged](https://cloud.githubusercontent.com/assets/8060988/20354458/82c04844-ac1e-11e6-831d-297d97b2c98c.jpg)

**Comment by tpayen** [comment]
Hi,
The new 0.4.6 release for plugin and skin add the Filter in the footer when you're in search mode.
