### ISSUE TITLE
Compatibility with enigma

### ISSUE THREAD

**Issue by mokas01** [messagerie-melanie2/Roundcube-Plugin-Mobile#16]
Hi,

I ([but not only I](https://github.com/roundcube/roundcubemail/issues/5444)) tried to use enigma and Roundcube-Plugin-Mobile together, but once the mobile plugin is active, the prompt for the password of enigma can't appear and there is no way to decrypt messages on mobile.
Is there a way to render the prompt in this plugin for us not to choose between mobile and private ?

Thanks in advance

**Comment by tpayen** [comment]
Hello,
I've started to implement enigma support in mobile skin with the 0.4.6 release.
It's not perfect but I think it's usable for a start

**Comment by mokas01** [comment]
cheers !
