### ISSUE TITLE
Error plugins with roundcube 1.2.3

### ISSUE THREAD

**Issue by N45gu1** [messagerie-melanie2/Roundcube-Plugin-Mobile#18]
Hello,

Thank you very much for your job, it's great.

I have an error with roundcube 1.2.3:

PHP Error: Failed to load plugin file /var/www/roundcubemail/plugins/mobile/mobile.php in /var/www/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 173 (GET /?_task=settings)

It's possible to help me with this?

Thank you.
Best regards,
N1c0

**Comment by tpayen** [comment]
Hi,
Can you check if user www-data (or your http user) has read rights on /var/www/roundcubemail/plugins/mobile/ directory

**Comment by N45gu1** [comment]
Hi Thomas,
Thank you for your reply.

I changed the user www-data in my vhost but my user www-roundcube has read rights on mobile directory and it's not work.

**Comment by tpayen** [comment]
Hmm it's weird because it's clearly a rights problem, line 173 of rcube_plugin_api.php check if the file mobile.php is readable

**Comment by N45gu1** [comment]
I found my error, I had reversed the directories in plugins.
Sorry for this and thank you for your help.
Best regards,
N1c0
