### ISSUE TITLE
compatibility with managesieve plugin

### ISSUE THREAD

**Issue by chris-asdf** [messagerie-melanie2/Roundcube-Plugin-Mobile#22]
Hi,

The managesieve plugin is not usable. It's settingspage won't load (Error 404).
Reason is, managesieve plugin ships own templates and styles for larry and classic skins, but there is no definition for a mobile skin.

Just copying the folder larry to melanie2_larry_mobile borks the layout, obviously.

Roundcube version: 1.2.3
melanie2_larry_mobile version: master as of 12/11/2016
managesieve plugin as shipped with roundcube

Best Regards
Chris

**Comment by tpayen** [comment]
With the last release (v0.4.7) you can find a "plugins" directory that provides melanie2_larry_mobile skin for the managesieve plugin

**Comment by chris-asdf** [comment]
Thanks for clearing this up. I missed that already fixed issue.

**Comment by chris-asdf** [comment]
I've just discovered, if there are more than one filterset, only the topmost is displayed. In the template of the larry skin there is a pane for selecting filtersets (id: filtersetslist).
Could this enhanced, please?
