### ISSUE TITLE
php warning: Missing argument 1 ... in plugins/mobile/mobile.php on line 334

### ISSUE THREAD

**Issue by chris-asdf** [messagerie-melanie2/Roundcube-Plugin-Mobile#23]
Hi

Everytime the avatar of the own identity is displayed (e.g. in folder view or the settings) the following Warning shows up in my log files:
Dec 15 18:05:57 <hostname> roundcube: PHP Warning:  Missing argument 1 for rcmail_output_html::current_username(), called in /<path-to-roundcube>/plugins/mobile/mobile.php on line 334 and defined in /<path-to-roundcube>/program/include/rcmail_output_html.php on line 1750

Line 334 in mobile.php is the function userphoto(..). But my php-skills are scarce, so I have no idea how to fix it...

Versions:
php: 5.6.27
roundcube: 1.2.3
melanie2_mobile: master as of 12/11/2016

Any help is appreciated,
Chris

**Comment by tpayen** [comment]
Hello,
Please don't use master branch but the releases.
Your issue has already been reported here #21 and has been fix in release v0.4.7

**Comment by chris-asdf** [comment]
Thanks for clearing this up. I missed that already fixed issue.
