### ISSUE TITLE
Changing skin on desktop browser with error

### ISSUE THREAD

**Issue by rkd77** [messagerie-melanie2/Roundcube-Plugin-Mobile#24]
Hi,
When user attempt to change the webmail skin, its fail.

How to:
Login mail account
Go to "Settings"
Go to "User Interface"
Change "Interface skin" from "Classic" to "Mélanie2 Larry mobile" and hit "Save"
Now attempt to change from Mélanie2 Larry mobile to Classic
Actually: 

Warning: Invalid argument supplied for foreach() in /mail/program/steps/settings/edit_prefs.inc on line 57

Or without any errors but when we click "Save" - nothing happens. After reload the page changes come into force

Other minor issue is not changed version in composer.json

**Comment by tpayen** [comment]
Hi,
In fact you don't have to change the skin in the settings. The switch is automatic or you can use the "Mobile view" link on top left of the page.
If you want to prevent your users from switching skins in settings you can add "skin" in 'dont_override' property in the config file

**Comment by rkd77** [comment]
Sorry, I did not express it clearly.
For desktop users (for example laptop users), Mélanie2 Larry mobile is visible as normal skin.
User can switch to this skin, but when he/she wants to go back to previous skin (for example classic), it is not done automatically. User must reload page. It is not intuitive.

**Comment by tpayen** [comment]
This is because you mustn't switch to mobile skin in settings.
Unfortunatly there is no option for hiding a skin in settings, but like I said you can add skin in dont override property.
