### ISSUE TITLE
Display attachments

### ISSUE THREAD

**Issue by lgautrot** [messagerie-melanie2/Roundcube-Plugin-Mobile#3]
Hello,

I can see pictures at the end of an email body (1-image_preview_mobile_skin.png) , in somewhat the same way as  I can see it on the preview pane of the desktop skin.

When the attachment is not an image file, there's not even a download icon, although you can find such an icon on the desktop skin (2-attachments_pane_desktop_skin.png).

Even i I can see an icon on the maillist in mobile skin meaning there is at least one attachment in the email (3-attachment_icon_maillist_mobile_skin.png), I can't see the list of attachments in the mail preview (4-mail_preview_mobile_skin.png).

Can you please tell me if there's something wrong in my client. By the way, the screenshots have been taken on a desktop but the android version of firefox display the same.

Best regards

![1-image_preview_mobile_skin](https://cloud.githubusercontent.com/assets/467767/9543800/1ced3aba-4d7c-11e5-831d-44df6f8ab453.png)
![2-attachments_pane_desktop_skin](https://cloud.githubusercontent.com/assets/467767/9543799/1ce9f53a-4d7c-11e5-9c20-6fa7a1dc5650.png)
![3-attachment_icon_maillist_mobile_skin](https://cloud.githubusercontent.com/assets/467767/9543801/1ced7bb0-4d7c-11e5-8e86-046beea75225.png)
![4-mail_preview_mobile_skin](https://cloud.githubusercontent.com/assets/467767/9543802/1cee1836-4d7c-11e5-90a2-964b082268a1.png)

**Comment by tpayen** [comment]
The attachments list is although displayed, it is between the header and the body.
For images attachments, a thumbnail is indeed displayed below the body

![roundcube mobile](https://cloud.githubusercontent.com/assets/3693239/9546524/a1200094-4d93-11e5-8eeb-63d0295e1375.png)

**Comment by lgautrot** [comment]
Hi Tom,

thanks for your quick reply. I just had a look at an email containing the same file types (ODT/ODS). And the point is that they're still not displayed on my setup.

I'll try to investigate and hopefully get some more information.

Best regards

**Comment by lgautrot** [comment]
Hi Tom,

so I have found that when I load the email, i does not contain the attachments list. When I reload the page, they are displayed.

Now I still have to understand why I get only one HTTP request when I try to display an email and why I get 27 when I reload (including many js, css and task GET requests).

The only visible difference I can notice is that the only request looks like "GET /roundcubemail/?_task=mail&_action=show&_uid=72517&_mbox=INBOX&_caps=pdf%3D0%2Cflash%3D0%2Ctif%3D0" when the attachments list does not show up.

When I reload the page, the request looks like : "GET /roundcubemail/?_task=mail&_action=show&_uid=72517&_mbox=INBOX&_caps=pdf=0,flash=0,tif=0". Then the several (about 25 requests fire up).

Best regards.

![1-before_reload](https://cloud.githubusercontent.com/assets/467767/9547217/063fdfee-4d99-11e5-80ed-9c471e1411cd.png)
![2-after_reload](https://cloud.githubusercontent.com/assets/467767/9547218/0646d236-4d99-11e5-9db4-686ad2f62100.png)

**Comment by tpayen** [comment]
This is because there is 2 ways for displaying a message :
- When opening a message by clicking in the messages list, the message is loaded by ajax. So it only loads the message content and no css or javascript. And messages list is still displayed on the page, so when you go back you return exactly where you were.
- When reloading the message, all the page is reloaded. So it loads the page content, css files and javascript files. 

So reloading the page fixes the problem. But open a message from the list should show attachments.
Do you see errors in the console log (shift + F5) when you are opening a message with attachments ?

**Comment by tpayen** [comment]
Hi,
I've just published a new release that correct the problem : https://github.com/messagerie-melanie2/roundcube_mobile/releases/tag/v0.4.3
