### ISSUE TITLE
navigation gets stuck at MAIL wont change folder until open in new tab

### ISSUE THREAD

**Issue by johnwayne4d** [messagerie-melanie2/Roundcube-Plugin-Mobile#5]
running roundcube 1.1.3 upgraded from 1.1.0 . after login user finds themselves in MAIL. cannot change folder via hamburger icon. if holding down on folder item past hamburger icon, then choosing open in new tab - then folders change, and all works normal until MAIL is chosen from right side menu, then problem repeats.

**Comment by tpayen** [comment]
Hi,
Which device and web browser do you use?

**Comment by johnwayne4d** [comment]
please see my other new issue request. my apologies for not closing this one sooner. I am running an updated system now, and the above was other issues combined with the mobile safari bug which required a roundcube edit.
